mod 'keystone',         :git => 'https://github.com/openstack/puppet-keystone.git',         :ref => 'stable/kilo'
mod 'nova',             :git => 'https://github.com/openstack/puppet-nova.git',             :ref => 'stable/kilo'
mod 'cinder',           :git => 'https://github.com/openstack/puppet-cinder.git',           :ref => 'stable/kilo'
mod 'glance',           :git => 'https://github.com/openstack/puppet-glance.git',           :ref => 'stable/kilo'
mod 'neutron',          :git => 'https://github.com/openstack/puppet-neutron.git',          :ref => 'stable/kilo'
mod 'openstacklib',     :git => 'https://github.com/openstack/puppet-openstacklib.git',     :ref => 'stable/kilo'
mod 'openstack_extras', :git => 'https://github.com/openstack/puppet-openstack_extras.git', :ref => 'stable/kilo'
mod 'vswitch',          :git => 'https://github.com/openstack/puppet-vswitch.git'
mod 'apache',           :git => 'https://github.com/puppetlabs/puppetlabs-apache.git'
mod 'inifile',          :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
mod 'stdlib',           :git => 'https://github.com/puppetlabs/puppetlabs-inifile.git'
mod 'rabbitmq',         :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git'
mod 'mysql',            :git => 'https://github.com/puppetlabs/puppetlabs-mysql.git'
mod 'sysctl',           :git => 'https://github.com/duritong/puppet-sysctl.git'
mod 'epel',             :git => 'https://github.com/stahnma/puppet-module-epel.git'
mod 'staging',          :git => 'https://github.com/nanliu/puppet-staging.git'
mod 'puppetdb',         :git => 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
mod 'firewall',         :git => 'https://github.com/puppetlabs/puppetlabs-firewall.git'
mod 'network',          :git => 'https://github.com/puppet-community/puppet-network.git'
